version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing app dependencies...
      - yarn install
  build:
    commands:
      - echo Building...
      - yarn build
      - echo Testing...
      - yarn test
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist

cache:
  paths:
    - './node_modules/**/*'