version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing app dependencies...
      - yarn install
  build:
    commands:
      - echo Building...
      - yarn build

cache:
  paths:
    - './node_modules/**/*'